server:
  port: 8000

spring:
  application:
    name: short-link-gateway
  profiles:
    active: dev
  data:
    redis:
      host: 192.168.154.130
      port: 6379
      password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848